version: 0.2

phases:
  pre_build:
    commands:
      - echo "PRE-BUILD PHASE"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - BUILD_NUMBER=$(echo $CODEBUILD_BUILD_ID | cut -d: -f1 | cut -d/ -f2)
      - BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///' | sed 's/\//-/g')
      - test -z "$BRANCH_NAME" && BRANCH_NAME="unknown"
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo "Repository - $REPOSITORY_URI"
      - echo "Branch - $BRANCH_NAME"
      - echo "Commit - $COMMIT_HASH"
      - echo "Logging in to ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "BUILD PHASE"
      - echo "Building Docker image"
      - docker build -t $REPOSITORY_URI:$COMMIT_HASH .
      - docker tag $REPOSITORY_URI:$COMMIT_HASH $REPOSITORY_URI:build-$BUILD_NUMBER

  post_build:
    commands:
      - echo "POST-BUILD PHASE"
      - TIMESTAMP=$(date +%Y%m%d-%H%M%S)
      - echo "Pushing commit hash tag"
      - docker push $REPOSITORY_URI:$COMMIT_HASH
      - echo "Pushing build number tag"
      - docker push $REPOSITORY_URI:build-$BUILD_NUMBER
      - sh -c 'if [ "$BRANCH_NAME" = "main" ]; then docker tag $REPOSITORY_URI:$COMMIT_HASH $REPOSITORY_URI:latest && docker push $REPOSITORY_URI:latest && docker tag $REPOSITORY_URI:$COMMIT_HASH $REPOSITORY_URI:stable && docker push $REPOSITORY_URI:stable && echo "prod-$COMMIT_HASH-$TIMESTAMP" > semantic_tag.txt; fi'
      - sh -c 'if [ "$BRANCH_NAME" = "staging" ]; then docker tag $REPOSITORY_URI:$COMMIT_HASH $REPOSITORY_URI:staging-latest && docker push $REPOSITORY_URI:staging-latest && echo "staging-$COMMIT_HASH-$TIMESTAMP" > semantic_tag.txt; fi'
      - sh -c 'if [ "$BRANCH_NAME" = "develop" ]; then docker tag $REPOSITORY_URI:$COMMIT_HASH $REPOSITORY_URI:dev-latest && docker push $REPOSITORY_URI:dev-latest && echo "dev-$COMMIT_HASH-$TIMESTAMP" > semantic_tag.txt; fi'
      - test -f semantic_tag.txt || echo "$BRANCH_NAME-$COMMIT_HASH-$TIMESTAMP" > semantic_tag.txt
      - SEMANTIC_TAG=$(cat semantic_tag.txt)
      - echo "Semantic tag - $SEMANTIC_TAG"
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$COMMIT_HASH > imagedefinitions.json
      - printf '{"commitHash":"%s","branchName":"%s","semanticTag":"%s","timestamp":"%s"}' "$COMMIT_HASH" "$BRANCH_NAME" "$SEMANTIC_TAG" "$TIMESTAMP" > build-metadata.json
      - echo "BUILD COMPLETED"

artifacts:
  files:
    - imagedefinitions.json
    - build-metadata.json
