version: 0.2

phases:
  pre_build:
    commands:
      - echo "================================================"
      - echo "PRE-BUILD PHASE - $(date)"
      - echo "================================================"
      - echo "Extracting build information..."
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - FULL_COMMIT_HASH=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - BUILD_ID=$CODEBUILD_BUILD_ID
      - BUILD_NUMBER=$(echo $BUILD_ID | cut -d: -f1 | cut -d/ -f2)
      - |
        if [ ! -z "$CODEBUILD_WEBHOOK_HEAD_REF" ]; then
          BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///' | sed 's/\/\//-/g')
          echo "Branch detected from webhook: $BRANCH_NAME"
        else
          BRANCH_NAME="unknown"
          echo "Warning: Branch name not detected, using 'unknown'"
        fi
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo "------------------------------------------------"
      - echo "Build Information:"
      - echo "  Repository URI: $REPOSITORY_URI"
      - echo "  Branch: $BRANCH_NAME"
      - echo "  Commit Hash: $COMMIT_HASH"
      - echo "  Full Commit: $FULL_COMMIT_HASH"
      - echo "  Build ID: $BUILD_ID"
      - echo "  Build Number: $BUILD_NUMBER"
      - echo "  Region: $AWS_DEFAULT_REGION"
      - echo "  Account ID: $AWS_ACCOUNT_ID"
      - echo "------------------------------------------------"
      - echo "Logging in to Amazon ECR..."
      - |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION \
        | docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Successfully logged in to ECR"
      - |
        echo "Checking if ECR repository exists..."
        if ! aws ecr describe-repositories \
          --repository-names $IMAGE_REPO_NAME \
          --region $AWS_DEFAULT_REGION 2>/dev/null; then
          echo "ECR repository $IMAGE_REPO_NAME not found!"
          exit 1
        fi
        echo "ECR repository exists"

  build:
    commands:
      - echo "================================================"
      - echo "BUILD PHASE - $(date)"
      - echo "================================================"
      - echo "Building Docker image..."
      - |
        docker build \
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
          --build-arg VCS_REF=$COMMIT_HASH \
          --build-arg VERSION=$BRANCH_NAME-$COMMIT_HASH \
          --build-arg BUILD_NUMBER=$BUILD_NUMBER \
          -t $REPOSITORY_URI:$COMMIT_HASH \
          -t $REPOSITORY_URI:build-$BUILD_NUMBER \
          -t $REPOSITORY_URI:latest-build \
          .
      - docker images | grep "$IMAGE_REPO_NAME"

  post_build:
    commands:
      - echo "================================================"
      - echo "POST-BUILD PHASE - $(date)"
      - echo "================================================"
      - docker push $REPOSITORY_URI:$COMMIT_HASH
      - docker push $REPOSITORY_URI:build-$BUILD_NUMBER
      - docker push $REPOSITORY_URI:latest-build
      - |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        SEMANTIC_TAG="${BRANCH_NAME}-${COMMIT_HASH}-${TIMESTAMP}"
        docker tag $REPOSITORY_URI:$COMMIT_HASH $REPOSITORY_URI:$SEMANTIC_TAG
        docker push $REPOSITORY_URI:$SEMANTIC_TAG
        echo "semantic_tag=$SEMANTIC_TAG" > semantic_tag.txt
      - |
        printf '[{"name":"%s","imageUri":"%s"}]' \
        "$CONTAINER_NAME" \
        "$REPOSITORY_URI:$COMMIT_HASH" \
        > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - build-metadata.json
    - build-summary.txt
  name: "BuildArtifacts-${CODEBUILD_BUILD_NUMBER}"

cache:
  paths:
    - "/root/.docker/**/*"
    - "/var/lib/docker/**/*"
